### ISSUE TITLE
Images not showing up on Github Pages

### ISSUE THREAD

**Issue by bwnstck** [AlexisRoe/my-personal-portfolio#7]
Referencing to  my own code: https://github.com/bwnstck/bootstrap-portfolio/commit/3328aa80

Same Problem on your site:
https://github.com/AlexisRoe/my-personal-portfolio/blob/e6d673fc130fcafb283c1fa2dcb87096f2a9df16/scss/custom.scss#L42

changing the path to absolute could fix the problem of pictures not showing on Github Pages
` background-image: url('https://alexisroe.github.io/my-personal-portfolio/images/cover.jpg'); `

Actual picture path with error 404:
https://alexisroe.github.io/images/cover.jpg

Picture found at:
https://alexisroe.github.io/my-personal-portfolio/images/cover.jpg

**Comment by AlexisRoe** [comment]
thanks for the information, i will correct my code

**Comment by bwnstck** [comment]
should work with relative path `url(../images/cover.jpg) `as well

**Comment by AlexisRoe** [comment]
it doesnt, 🤷‍♂️, but it doesnt matter, now it works
